### ISSUE TITLE
hex.pm spawn_co_elixir's github link can be fixed?

### ISSUE THREAD

**Issue by pojiro** [zeam-vm/pelemay_backend#387]
The link destination of the attached capture is https://github.com/zeam-vm/pelemay_backend.

It might be more convenient to link to, for example, https://github.com/zeam-vm/pelemay_backend/tree/main/utilities/spawn_co_elixir.

![image](https://github.com/zeam-vm/pelemay_backend/assets/4096956/5c35cb8b-27c9-4d52-bdd6-cae3b3e8a8bf)

**Comment by zacky1972** [comment]
Thank you for this first issue by other than the development team!

I guess this status is not wrong, because Nx adopts the similar way. See the Nx hex: https://hex.pm/packages/nx

**Comment by pojiro** [comment]
> I guess this status is not wrong, because Nx adopts the similar way. See the Nx hex: https://hex.pm/packages/nx

Thanks for your quick reply! I understand that you are doing the same thing as Nx, thx.

**Comment by zacky1972** [comment]
In addition, `README.md` describes the module with the link to the path.
